import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence, LayoutGroup } from 'framer-motion';
import { 
  LineChart, Line, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, 
  Radar, ResponsiveContainer, XAxis, YAxis, Tooltip, CartesianGrid 
} from 'recharts';
import { 
  ArrowLeft, Activity, ShieldCheck, AlertTriangle, Zap, 
  X, Info, CheckCircle, ChevronRight, Table 
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import axios from 'axios';

const INSIGHTS = {
  rom: {
    title: "Joint Range of Motion",
    whatItMeans: "Range of Motion (ROM) measures the flexibility of your joints. Consistent training increases this range over time.",
    advice: "Your trend is positive. Focus on full extension during every rep to maintain these gains.",
    metric: "Flexion Degrees"
  },
  symmetry: {
    title: "Symmetry & Balance",
    whatItMeans: "Compares strength between your left and right sides. Ideally, the difference should be under 10%.",
    advice: "If asymmetry is high, perform 2 extra sets on your weaker side to restore balance.",
    metric: "Imbalance Score"
  },
  hotspots: {
    title: "Error Hotspots",
    whatItMeans: "A heatmap of where your form tends to break down. Red areas indicate frequent stability issues.",
    advice: "Check the red zones. Reduce weight and focus purely on form to correct these patterns.",
    metric: "Error Frequency"
  },
  comparison: {
    title: "Session History",
    whatItMeans: "A complete log of every workout, allowing you to track granular improvements in accuracy and reps.",
    advice: "Consistency is key. Aim to keep your Accuracy above 85% for every single session.",
    metric: "Historical Data"
  },
  recommendations: {
    title: "AI Recommendations",
    whatItMeans: "Smart directives generated by analyzing your biomechanics over the last 5 sessions.",
    advice: "Follow these closely. They adapt automatically as you improve.",
    metric: "Action Items"
  }
};

const RiskPrediction = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedId, setSelectedId] = useState(null); 

  useEffect(() => {
    const fetchData = async () => {
      if (user?.email) {
        try {
          const res = await axios.post('http://127.0.0.1:5000/api/user/ai_prediction', { email: user.email });
          setData(res.data);
        } catch (err) {
          console.error(err);
        } finally {
          setLoading(false);
        }
      }
    };
    fetchData();
  }, [user]);

  if (loading) return <div style={{ height: '100vh', display: 'flex', justifyContent: 'center', alignItems: 'center', background: '#F9F7F3', color:'#666' }}>Analyzing...</div>;
  if (!data) return <div style={{padding:'50px'}}>No data found.</div>;

  const radarData = [
    { subject: 'Right', A: data.asymmetry.right, fullMark: 150 },
    { subject: 'Left', A: data.asymmetry.left, fullMark: 150 },
    { subject: 'Stability', A: data.stability_score, fullMark: 100 },
    { subject: 'ROM', A: data.rom_chart.length > 0 ? data.rom_chart[data.rom_chart.length-1].rom : 0, fullMark: 180 },
  ];

  const cards = [
    {
      id: 'rom',
      color: '#2C5D31',
      icon: Activity,
      title: 'Joint Range of Motion',
      colSpan: 1,
      content: (
        <div style={{ height: '100%', width: '100%', minHeight: '200px' }}>
            {data.rom_chart && data.rom_chart.length > 1 ? (
                <ResponsiveContainer>
                    <LineChart data={data.rom_chart}>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eee" />
                        <XAxis dataKey="date" stroke="#999" tick={{fontSize: 10}} />
                        <YAxis stroke="#999" tick={{fontSize: 10}} domain={[0, 180]} />
                        <Tooltip contentStyle={{ borderRadius: '10px' }} />
                        <Line type="monotone" dataKey="rom" stroke="#2C5D31" strokeWidth={3} dot={{r: 4}} />
                    </LineChart>
                </ResponsiveContainer>
            ) : (
                <div style={{height:'100%', display:'flex', alignItems:'center', justifyContent:'center', color:'#999', fontSize:'0.9rem'}}>
                    Not enough data for chart yet.
                </div>
            )}
        </div>
      )
    },
    {
      id: 'symmetry',
      color: '#FF9800',
      icon: Zap,
      title: 'Symmetry Score',
      colSpan: 1,
      content: (
        <div style={{ height: '100%', width: '100%', minHeight: '200px', position: 'relative' }}>
            <ResponsiveContainer>
                <RadarChart cx="50%" cy="50%" outerRadius="70%" data={radarData}>
                    <PolarGrid stroke="#eee" />
                    <PolarAngleAxis dataKey="subject" tick={{fontSize: 10, fill: '#666'}} />
                    <PolarRadiusAxis angle={30} domain={[0, 150]} hide />
                    <Radar name="Metrics" dataKey="A" stroke="#FF9800" fill="#FF9800" fillOpacity={0.5} />
                    <Tooltip />
                </RadarChart>
            </ResponsiveContainer>
            <div style={{ position:'absolute', bottom: 0, width:'100%', textAlign:'center', fontSize:'0.9rem', color:'#666' }}>
                Imbalance: <span style={{fontWeight:'bold', color: data.asymmetry.score > 15 ? '#D32F2F' : '#2C5D31'}}>{data.asymmetry.score}%</span>
            </div>
        </div>
      )
    },
    {
      id: 'hotspots',
      color: '#D32F2F',
      icon: AlertTriangle,
      title: 'Error Hotspots',
      colSpan: 1,
      content: (
        <div style={{ height: '100%', width: '100%', minHeight: '200px', display: 'flex', justifyContent: 'center', position: 'relative' }}>
            <svg height="200" viewBox="0 0 100 200" fill="#e0e0e0">
                <circle cx="50" cy="20" r="15" />
                <rect x="35" y="35" width="30" height="70" rx="5" />
                <rect x="15" y="40" width="15" height="60" rx="5" />
                <rect x="70" y="40" width="15" height="60" rx="5" />
                <rect x="30" y="110" width="12" height="80" rx="5" />
                <rect x="58" y="110" width="12" height="80" rx="5" />
            </svg>
            <motion.div animate={{ scale: [1, 1.2, 1] }} transition={{ repeat: Infinity, duration: 2 }} style={{ position: 'absolute', top: '50px', right: '110px', width: '20px', height: '20px', borderRadius: '50%', background: `rgba(211, 47, 47, ${data.hotspots.shoulder/50})`, border: '2px solid white' }} />
            <motion.div animate={{ scale: [1, 1.2, 1] }} transition={{ repeat: Infinity, duration: 2, delay: 0.5 }} style={{ position: 'absolute', top: '90px', right: '100px', width: '15px', height: '15px', borderRadius: '50%', background: `rgba(255, 152, 0, ${data.hotspots.elbow/30})`, border: '2px solid white' }} />
        </div>
      )
    },
    {
      id: 'recommendations',
      color: '#2C5D31',
      icon: ShieldCheck,
      title: 'AI Recommendations',
      colSpan: 1,
      content: (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {data.recommendations.map((rec, i) => (
                <div key={i} style={{ background: '#F1F8E9', padding: '12px', borderRadius: '10px', color: '#33691E', fontSize: '0.9rem', display: 'flex', gap: '10px', alignItems: 'start' }}>
                    <CheckCircle size={16} style={{marginTop:'3px', flexShrink: 0}} />
                    {rec}
                </div>
            ))}
        </div>
      )
    },
    {
      id: 'comparison',
      color: '#69B341',
      icon: Table,
      title: 'Session Comparison',
      colSpan: 2, 
      content: (
        <div style={{ overflowX: 'auto', marginTop: '10px' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.9rem' }}>
                <thead>
                    <tr style={{ borderBottom: '2px solid #f0f0f0', textAlign: 'left' }}>
                        <th style={{ padding: '10px', color: '#888' }}>Date</th>
                        <th style={{ padding: '10px', color: '#888' }}>Accuracy</th>
                        <th style={{ padding: '10px', color: '#888' }}>Reps</th>
                        <th style={{ padding: '10px', color: '#888' }}>ROM</th>
                        <th style={{ padding: '10px', color: '#888' }}>Errors</th>
                    </tr>
                </thead>
                <tbody>
                    {data.session_history && data.session_history.slice(0, 5).map((session, i) => (
                        <tr key={i} style={{ borderBottom: '1px solid #f9f9f9' }}>
                            <td style={{ padding: '12px 10px', fontWeight: '600', color: '#444' }}>{session.date}</td>
                            <td style={{ padding: '12px 10px' }}><span style={{ padding: '4px 8px', borderRadius: '12px', fontSize: '0.8rem', fontWeight: 'bold', background: session.accuracy > 80 ? '#E8F5E9' : '#FFEBEE', color: session.accuracy > 80 ? '#2C5D31' : '#D32F2F' }}>{session.accuracy}%</span></td>
                            <td style={{ padding: '12px 10px', color: '#666' }}>{session.reps}</td>
                            <td style={{ padding: '12px 10px', color: '#666' }}>{session.rom}°</td>
                            <td style={{ padding: '12px 10px', color: session.errors > 0 ? '#D32F2F' : '#ccc' }}>{session.errors}</td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
      )
    }
  ];

  return (
    <div style={{ minHeight: '100vh', background: '#F9F7F3', padding: '40px 5%', overflowX: 'hidden' }}>
      <div style={{ maxWidth: '1400px', margin: '0 auto' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px' }}>
          <div>
            <h1 style={{ fontSize: '2.5rem', fontWeight: '800', color: '#1A3C34', margin: 0 }}>
              AI Recovery <span style={{color:'#69B341'}}>Prediction</span>
            </h1>
            <p style={{ color: '#666', marginTop: '5px' }}>{selectedId ? "Deep Dive Analysis" : "Select a card to view insights."}</p>
          </div>
          <button onClick={() => navigate('/profile/overview')} style={{ background: '#fff', border: '1px solid #ddd', padding: '10px 20px', borderRadius: '30px', cursor:'pointer' }}>Back</button>
        </div>

        <LayoutGroup>
            <motion.div layout style={{ display: 'flex', gap: '30px', flexDirection: selectedId ? 'row' : 'column' }}>
                
                {/* 1. GRID / SIDEBAR AREA */}
                <motion.div 
                    layout 
                    style={{ 
                        flex: selectedId ? 1 : 'none', 
                        display: 'grid', 
                        gridTemplateColumns: selectedId ? '1fr' : 'repeat(auto-fit, minmax(350px, 1fr))', 
                        gap: '20px', 
                        maxWidth: selectedId ? '350px' : '100%' 
                    }}
                >
                    <AnimatePresence>
                        {cards.filter(c => c.id !== selectedId).map(card => (
                            <motion.div 
                                key={card.id} 
                                layoutId={card.id}
                                onClick={() => setSelectedId(card.id)}
                                style={{ background: '#fff', borderRadius: '24px', padding: '25px', boxShadow: '0 5px 20px rgba(0,0,0,0.05)', cursor: 'pointer', border: '2px solid transparent', gridColumn: selectedId ? 'auto' : `span ${card.colSpan || 1}` }}
                                whileHover={{ y: -5, boxShadow: '0 10px 30px rgba(0,0,0,0.08)' }}
                            >
                                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '15px' }}>
                                    <div style={{ padding: '8px', borderRadius: '10px', background: `${card.color}20` }}><card.icon size={20} color={card.color} /></div>
                                    <h3 style={{ margin: 0, fontSize: '1.1rem', color: '#1A3C34' }}>{card.title}</h3>
                                </div>
                                {!selectedId && <div style={{height: '200px', overflow:'hidden', pointerEvents:'none'}}>{card.content}</div>}
                            </motion.div>
                        ))}
                    </AnimatePresence>
                </motion.div>

                {/* 2. EXPANDED DETAIL AREA */}
                <AnimatePresence mode='popLayout'>
                    {selectedId && (() => {
                        const activeCard = cards.find(c => c.id === selectedId);
                        const insight = INSIGHTS[selectedId];
                        return (
                            <motion.div 
                                key="detail"
                                layoutId={selectedId}
                                initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, scale: 0.95 }}
                                style={{ flex: 3, background: '#fff', borderRadius: '30px', padding: '40px', boxShadow: '0 20px 50px rgba(0,0,0,0.05)', position: 'relative' }}
                            >
                                <button onClick={() => setSelectedId(null)} style={{ position: 'absolute', top: '30px', right: '30px', background: '#f5f5f5', border: 'none', padding: '10px', borderRadius: '50%', cursor: 'pointer', zIndex: 10 }}><X size={20} color="#666" /></button>
                                
                                <div style={{ display: 'flex', alignItems: 'center', gap: '15px', marginBottom: '30px' }}>
                                    <div style={{ padding: '12px', borderRadius: '14px', background: `${activeCard.color}20` }}><activeCard.icon size={32} color={activeCard.color} /></div>
                                    <div>
                                        <h2 style={{ margin: 0, fontSize: '2rem', color: '#1A3C34' }}>{activeCard.title}</h2>
                                        <span style={{ color: activeCard.color, fontWeight: '600', fontSize: '0.9rem', letterSpacing: '1px', textTransform: 'uppercase' }}>{insight.metric}</span>
                                    </div>
                                </div>

                                <div style={{ minHeight: '400px', marginBottom: '40px', background: '#FAFAFA', borderRadius: '20px', padding: '30px' }}>
                                    {activeCard.content}
                                </div>

                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '30px' }}>
                                    <div>
                                        <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#1A3C34', marginBottom: '10px' }}><Info size={18} /> What does this mean?</h4>
                                        <p style={{ color: '#666', lineHeight: '1.6' }}>{insight.whatItMeans}</p>
                                    </div>
                                    <div style={{ background: `${activeCard.color}10`, padding: '20px', borderRadius: '15px', borderLeft: `4px solid ${activeCard.color}` }}>
                                        <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', color: activeCard.color, marginBottom: '10px', marginTop: 0 }}><Zap size={18} /> Actionable Advice</h4>
                                        <p style={{ color: '#444', lineHeight: '1.6', margin: 0, fontWeight: '500' }}>{insight.advice}</p>
                                    </div>
                                </div>
                            </motion.div>
                        );
                    })()}
                </AnimatePresence>

            </motion.div>
        </LayoutGroup>
      </div>
    </div>
  );
};

export default RiskPrediction;